CREATE TABLE [dbo].[ActivityLog]
(
	[Id] UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT [DF_ActivityLogId] DEFAULT NEWSEQUENTIALID(),

	[ActivityLogType] VARCHAR(100) NOT NULL,

	CONSTRAINT [PK_ActivityLogId]
		PRIMARY KEY CLUSTERED ([Id]),
);