CREATE TABLE [dbo].[ActivityLog]
(
	[Id]					UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_ActivityLog_Id] DEFAULT NEWSEQUENTIALID(),
	[ActivityLogType]		VARCHAR(100)	 NOT NULL,

	CONSTRAINT [PK_ActivityLog] PRIMARY KEY CLUSTERED ([Id])
);
GO